### ISSUE TITLE
ship(subsection): Weapons and Equipment Sorting and Filtering

### ISSUE THREAD

**Issue by switchback77** [darklab8/fl-darkstat#17]
As requested, a copy-paste from our conversation on Discord:

Switchback — Today at 9:44 PM
Also just from a features request, being able to simulate loadouts would be super cool
[9:44 PM]
I'm not a programmer but they do exist

@Switchback
Also just from a features request, being able to simulate loadouts would be super cool

Darkwind — Today at 9:45 PM
I plan showing at least all ship gungun/equipment slots in a most easy to understand way(edited)

Switchback — Today at 9:46 PM
May get complex quickly tbh

Darkwind — Today at 9:46 PM
Stimulating loadout further... unsure

Switchback — Today at 9:46 PM
But if it's all automated that'd make things easier
[9:47 PM]
Even just having a hyperlink to "class 9 guns" would be cool

**Comment by dd84ai** [comment]
@switchback77 implemented Sorting and filtering and even compairson in [v.1.4.0 release](<https://discoverygc.com/forums/showthread.php?tid=187294&pid=2330617#pid2330617>)
