### ISSUE TITLE
Update for new Armor resistance

### ISSUE THREAD

**Issue by dd84ai** [darklab8/fl-darkstat#60]
in some next patch disco will have changed armor resistance to
`DamageReduction% = ArmorRating / (200 + ArmorRating)`

update relevant code :)

**Comment by Aingar** [comment]
the key for ships also changes from `armor_mult` to just `armor`, and the data type from `float` to `int`.
Expected results for a few values for purposes of unit tests:
0 armor = 0.00f = 0% reduction 
15 armor = 0.1304347826f = ~13% reduction
200 armor = 0.5f = 50% reduction

**Comment by dd84ai** [comment]
Nice. thanks.

**Comment by Aingar** [comment]
The formula is updated, instead of static 200 we will use 100. No other changes.

**Comment by dd84ai** [comment]
![Screenshot_20241201_201128](https://github.com/user-attachments/assets/8592cd48-50e3-4b62-8936-91cb0db7980a)
Updated stuff @Aingar on example of Bretonian gunboat all looks good. Commencing deployment
